//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLanguage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Feedback
    {
        
        public int Id { get; set; }

        [Column(TypeName = "date")]
        public string Date { get; set; }

        public string Email { get; set; }
        public string UserId { get; set; }

        [Range(0,10)]
        public string Rating { get; set; }
        public int UnitId { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
